# Generated by Django 2.1.3 on 2018-12-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20181130_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bio',
            field=models.TextField(default=None),
        ),
    ]
