# Generated by Django 2.1.3 on 2018-12-01 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_person_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='bio',
        ),
    ]
